# Generated by Django 5.0.3 on 2024-06-03 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0002_carreras_creacioncarrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMateria', models.CharField(max_length=100, verbose_name='Nombre de la materia')),
                ('DescripcionMateria', models.TextField(verbose_name='Descripcion de la materia')),
                ('CreacionMateria', models.DateTimeField(auto_now_add=True, verbose_name='creacion de la materia')),
                ('carreras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Materia', to='carreras.carreras')),
            ],
        ),
    ]
