# Generated by Django 5.0.3 on 2024-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='duraccionMateria',
            field=models.CharField(default=0, max_length=100, verbose_name='Duracion de la materia'),
            preserve_default=False,
        ),
    ]
