# Generated by Django 5.0.3 on 2024-06-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_duraccionmateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='imagenesMateria',
            field=models.ImageField(default="1", upload_to='Materias/'),
            preserve_default=False,
        ),
    ]
