# Generated by Django 5.0.3 on 2024-06-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_carreras_creacioncarrera'),
        ('estudiantes', '0003_alter_estudiantes_user'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera', to='carreras.carreras'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='materia',
            field=models.ManyToManyField(related_name='materia', to='materias.materia'),
        ),
    ]
