# Generated by Django 5.0.3 on 2024-06-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_alter_estudiantes_carrera_alter_estudiantes_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='apellido',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='email',
            field=models.EmailField(default='hola', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='nombre',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
