# Generated by Django 5.0.3 on 2024-06-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0006_alter_carreras_descripcioncarrera'),
        ('profesores', '0002_profesor_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='carrera',
            field=models.ManyToManyField(related_name='profesores', to='carreras.carreras'),
        ),
    ]
