# Generated by Django 5.0.3 on 2024-06-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_profesor_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='materia',
        ),
    ]
