# Generated by Django 5.0.3 on 2024-06-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0005_profesor_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='materia',
        ),
    ]
