# Generated by Django 5.0.3 on 2024-06-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0006_alter_carreras_descripcioncarrera'),
        ('materias', '0004_materia_profesor'),
        ('profesores', '0006_remove_profesor_carrera_remove_profesor_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='carrera',
            field=models.ManyToManyField(related_name='profesores', to='carreras.carreras'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materia',
            field=models.ManyToManyField(related_name='profesores_materias', to='materias.materia'),
        ),
    ]
