# Generated by Django 5.0.6 on 2024-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCarrera', models.CharField(max_length=100, verbose_name='Nombre de la Carrera')),
                ('DescripcionCarrera', models.TextField(verbose_name='Descripcion de la Carrera')),
                ('DuracionCarrera', models.CharField(max_length=100, verbose_name='Duración en Semestres')),
                ('CostoCarrera', models.IntegerField(verbose_name='Créditos')),
            ],
        ),
    ]
