# Generated by Django 5.0.6 on 2024-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careeras',
            fields=[
                ('idClass', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de Carrera')),
                ('nameClass', models.CharField(max_length=100, verbose_name='Nombre de la Carrera')),
                ('durationClass', models.IntegerField(verbose_name='Duración en Semestres')),
                ('creditClass', models.IntegerField(verbose_name='Créditos')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['idClass'],
            },
        ),
        migrations.DeleteModel(
            name='Carreras',
        ),
    ]
