# Generated by Django 5.0.3 on 2024-06-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_carreras_creacioncarrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='imagenesCarrera',
            field=models.ImageField(default='ImagenesCarreras', upload_to='Carreras/', verbose_name='Imagen de la carrera'),
            preserve_default=False,
        ),
    ]
