# Generated by Django 5.0.6 on 2024-06-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_careeras_delete_carreras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Careeras',
            new_name='Carreras',
        ),
    ]
