# Generated by Django 5.0.2 on 2024-04-10 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_article_image_alter_article_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('idClass', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de Carrera')),
                ('nameClass', models.CharField(max_length=100, verbose_name='Nombre de la Carrera')),
                ('durationClass', models.IntegerField(verbose_name='Duración en Semestres')),
                ('creditClass', models.IntegerField(verbose_name='Créditos')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['idClass'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=110)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LoginStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=110)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='public',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='article',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='create_date',
        ),
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('creditos', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.carrera')),
                ('profesores', models.ManyToManyField(to='miApp.profesor')),
            ],
        ),
    ]
